version: '3'

services:
  web:
    image: node:14
    container_name: mysql-container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
